### ISSUE TITLE
emailSender function doesn't use a queue

### ISSUE THREAD

**Issue by CameronWhiteCS** [OneCommunityGlobal/HGNRest#91]
The email system could be made easier to use and more reliable by replacing the current system with an email queue. When the emailSender function is called, the email is put into a queue rather than being immediately sent. 

Example of how the system currently works (taken from ![helpers/userhelper.js](https://github.com/OneCommunityGlobal/HGNRest/blob/development/src/helpers/userhelper.js)):

```js
timeoutMS += 500;
setTimeout(() => {
    emailSender(status.email, "New Infringment Assigned", getInfringmentEmailBody(status.firstName, status.lastName, infringment, status.infringments.length), null, "onecommunityglobal@gmail.com");
}, timeoutMS);
```

the ```timeoutMS``` variable is intended to avoid overwhelming the email system. Rather than code this multiple time across the back end, it makes more sense to build this functionality into a queue system.

**Comment by one-community** [comment]
Questions I have: 

Are there any potential downsides to this? 
Would it still work with gmail or use a different email? 
What are the benefits? You’ve said easier and more reliable, how?

**Comment by CameronWhiteCS** [comment]
**Are there any potential downsides to this?** None

**Would it still work with gmail or use a different email?** Same email

**What are the benefits? You’ve said easier and more reliable, how?** It eliminates possible programmer error and eliminates the possibility that the emailSender function is called at the same time by two separate threads which can result in one or more emails failing to be sent.

**Comment by one-community** [comment]
Sounds good, please proceed. Please add this to the Bugs Doc with your name on it too. I’d say it is “medium” priority.
